# Generated by Django 3.0.3 on 2020-02-27 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Management', '0001_initial'),
        ('Sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orders',
            field=models.ManyToManyField(through='Sale.Order_Product', to='Management.Order'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.Type'),
        ),
    ]
