# Generated by Django 3.0.3 on 2020-02-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_auto_20200228_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
