# Generated by Django 3.0.3 on 2020-03-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0013_auto_20200305_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.SmallIntegerField(),
        ),
    ]
