# Generated by Django 3.0.3 on 2020-03-05 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0014_auto_20200305_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amount',
            new_name='storage',
        ),
    ]
