# Generated by Django 3.0.3 on 2020-03-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0015_auto_20200305_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
