# Generated by Django 3.0.3 on 2020-03-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0016_auto_20200305_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateField(auto_now=True),
        ),
    ]
