# Generated by Django 3.0.3 on 2020-03-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0018_order_id_of_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id_of_order',
            field=models.CharField(max_length=6),
        ),
    ]
