# Generated by Django 3.0.3 on 2020-03-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0020_remove_order_id_of_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_all',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
