# Generated by Django 3.0.3 on 2020-03-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0023_save_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save_product',
            name='order',
        ),
        migrations.RemoveField(
            model_name='save_product',
            name='product',
        ),
    ]
