# Generated by Django 3.0.3 on 2020-03-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0025_auto_20200310_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save_product',
            name='name',
        ),
    ]
