# Generated by Django 3.0.3 on 2020-03-09 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0026_remove_save_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Save_Product',
        ),
    ]
