# Generated by Django 3.0.3 on 2020-03-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0027_delete_save_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_all',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
