# Generated by Django 3.0.3 on 2020-03-09 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sale', '0002_save_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Save_Product',
        ),
    ]
