# Generated by Django 3.0.3 on 2020-03-09 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sale', '0003_delete_save_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_all', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Sale.Order_Product')),
            ],
        ),
    ]
