# Generated by Django 3.0.3 on 2020-03-09 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0029_auto_20200310_0447'),
        ('Sale', '0007_save_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Order'),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Product'),
        ),
        migrations.AlterField(
            model_name='save_product',
            name='order_all',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sale.Order_Product'),
        ),
    ]
