# Generated by Django 3.0.3 on 2020-03-09 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sale', '0008_auto_20200310_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save_product',
            name='order_all',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Sale.Order_Product'),
        ),
    ]
