# Generated by Django 3.0.3 on 2020-03-10 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0030_auto_20200310_1936'),
        ('Sale', '0011_auto_20200310_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.Order'),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.Product'),
        ),
        migrations.DeleteModel(
            name='Save_Product',
        ),
    ]
