# Generated by Django 3.0.3 on 2020-03-10 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0030_auto_20200310_1936'),
        ('Sale', '0012_auto_20200310_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Product_Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_amount_all', models.IntegerField()),
                ('storage_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.Order')),
                ('storage_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.Product')),
            ],
        ),
    ]
